import Footer from "@/components/Footer";
import Navbar from "@/components/dashboard/Navbar";
import PanelMainSection from "@/components/dashboard/panel/PanelMainSection";
import PanelSidebar from "@/components/dashboard/panel/PanelSidebar";
import Head from "next/head";
import { useState } from "react";


export default function panel({ userData }) {
  const [mainSections, setMainSections] = useState("MyPanelHome");
  return (
    <div>
      <Head>
        <title>FreelancerHub - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar userData={userData} />
      <div className="flex">
        <div className="sidebar w-3/12 bg-white">
          <PanelSidebar
            setMainSections={setMainSections}
            mainSections={mainSections}
            userData={userData}
          />
        </div>
        <div className="hero w-9/12 bg-gray-100 p-10">
          <PanelMainSection
            userData={userData}
            setMainSections={setMainSections}
            mainSections={mainSections}
          />
        </div>
      </div>
      <Footer />
    </div>
  );
}

export async function getServerSideProps(context) {
  let userData = null;

  const token = context.req.cookies.token;

  if (token) {
    try {
      const res = await fetch(
        "http://localhost:5000/api/user/getUser",
        {
          method: "GET",
          headers: {
            Cookie: `token=${token}`,
          },
        },
        { withCredentials: true, credentials: "include" }
      );

      const data = await res.json();

      userData = data;
    } catch (error) {
      console.log(error.message);
      if (error.response) {
        console.log(error.response.data.message);
      }
    }
  }

  return {
    props: {
      userData,
    },
  };
}
