import { useEffect } from "react";
import Navbar from "../../components/dashboard/Navbar";
import { useRouter } from "next/router";
import axios from "axios";
import Sidebar from "../../components/dashboard/home/Sidebar";
import MainSection from "../../components/dashboard/home/MainSection";
import Footer from "../../components/Footer";
import Head from "next/head";

export default function Dashboard({ userData }) {
  // const token = cookies;
  // const router = useRouter();
  // useEffect(() => {
  //   if (!token) {
  //     router.push("/login");
  //   }
  // }, [token]);
  // useEffect(() => {
  //   document.getElementsByTagName("body")[0].style.backgroundColor = "#e9e9e9";
  // }, []);
  return (
    <>
      <Head>
        <title>FreelancerHub - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex justify-between items-center my-10">
        <Sidebar userData={userData} />
        <MainSection />
      </div>
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  let userData = null;

  const token = context.req.cookies.token; // Kullanıcının token'ını çerezlerden alın

  if (token) {
    try {
      const res = await fetch(
        "http://localhost:5000/api/user/getUser",
        {
          method: "GET",
          headers: {
            Cookie: `token=${token}`,
          },
        },
        { withCredentials: true, credentials: "include" }
      );

      const data = await res.json();
      console.log("json data", data);
      console.log(data[0].email);
      userData = data[0].email;
    } catch (error) {
      console.log(error.message);
      // if (error.response) {
      //   console.log(error.response.data.message);
      // }
    }
  }

  return {
    props: {
      userData,
    },
  };
}
