import { useEffect } from "react";
import Navbar from "../../components/dashboard/Navbar";
import { useRouter } from "next/router";

import Sidebar from "../../components/dashboard/home/Sidebar";
import MainSection from "../../components/dashboard/home/MainSection";
import Footer from "../../components/Footer";
import Head from "next/head";

export default function Dashboard({ cookies }) {
  const token = cookies;
  const router = useRouter();
  useEffect(() => {
    if (!token) {
      router.push("/login");
    }
  }, [token]);
  useEffect(() => {
    document.getElementsByTagName("body")[0].style.backgroundColor = "#e9e9e9";
  }, []);
  return (
    <>
     <Head>
        <title>FreelancerHub - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex justify-between items-center my-10">
        <Sidebar />
        <MainSection />
      </div>
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const cookies = context.req.headers.cookie;
  // console.log(cookies);
  return {
    props: { cookies },
  };
}
