import Navbar from "../../components/dashboard/Navbar";
import Sidebar from "../../components/dashboard/home/Sidebar";
import MainSection from "../../components/dashboard/home/MainSection";
import Footer from "../../components/Footer";
import Head from "next/head";

export default function Dashboard({ userData }) {
  console.log(userData)
  return (
    <>
      <Head>
        <title>FreelancerHub - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar userData={userData} />
      <div className="flex justify-between items-center my-10">
        <Sidebar userData={userData} />
        <MainSection userData={userData} />
      </div>
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  let userData = null;

  const token = context.req.cookies.token;

  if (token) {
    try {
      const res = await fetch(
        "http://localhost:5000/api/user/getUser",
        {
          method: "GET",
          headers: {
            Cookie: `token=${token}`,
          },
        },
        { withCredentials: true, credentials: "include" }
      );

      const data = await res.json();

      userData = data;
    } catch (error) {
      console.log(error.message);
      if (error.response) {
        console.log(error.response.data.message);
      }
    }
  }

  return {
    props: {
      userData,
    },
  };
}
