import Head from "next/head";
import HomePage from "../../components/HomePage";
import { useEffect } from "react";
import { useDispatch } from "react-redux";
import { setUserData } from "@/store/slices/userdata.slice";

export default function Home({ cookies, userData }) {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(setUserData(userData));
  }, []);

  return (
    <>
      <Head>
        <title>Freelancer Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage cookies={cookies.token} userData={userData} />
    </>
  );
}

// export async function getServerSideProps(context) {
//   const cookies = context.req.headers.cookie;

//   return {
//     props: cookies
//       ? {
//           cookies,
//         }
//       : { cookies: null },
//   };
// }

export async function getServerSideProps(context) {
  let userData = null;

  const token = context.req.cookies.token;

  if (token) {
    try {
      const res = await fetch(
        "http://localhost:5000/api/user/getUser",
        {
          method: "GET",
          headers: {
            Cookie: `token=${token}`,
          },
        },
        { withCredentials: true, credentials: "include" }
      );

      const data = await res.json();

      userData = data;
    } catch (error) {
      console.log(error.message);
      if (error.response) {
        console.log(error.response.data.message);
      }
    }
  }

  return {
    props: {
      userData,
      cookies: token
        ? {
            token,
          }
        : { token: null },
    },
  };
}
