import Head from "next/head";
import HomePage from "../../components/HomePage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Freelancer Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  );
}

export async function getServerSideProps(context) {
  const cookies = context.req.headers.cookie;
  console.log(cookies);
  return {
    props: {},
  };
}
