import Head from "next/head";
import Navbar from "../../components/dashboard/Navbar";
import Sidebar from "../../components/dashboard/settings/Sidebar";
import MainSection from "../../components/dashboard/settings/MainSection";
import Footer from "../../components/Footer";
import { useState } from "react";

export default function Settings() {
  const [mainSections, setMainSections] = useState("GeneralSettings");
  return (
    <div>
      <Head>
        <title>FreelancerHub - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex">
        <div className="sidebar w-3/12 bg-white">
          <Sidebar
            setMainSections={setMainSections}
            mainSections={mainSections}
          />
        </div>
        <div className="hero w-9/12 bg-gray-100 p-10">
          <MainSection
            setMainSections={setMainSections}
            mainSections={mainSections}
          />
        </div>
      </div>
      <Footer />
    </div>
  );
}
